seed: 32

clients:
  - count: 10
    speed: 8.
    cpus: 4
    work_fetch_interval: 3300.
    buffered_work_lower_bound: 3000.
    buffered_work_upper_bound: 12000.
    memory: 4
    disk_capacity: 5000
    disk_read_bandwidth: 2000.
    disk_write_bandwidth: 2000.
    network_latency: 0.5
    network_bandwidth: 1000
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 6000.


job_generator:
  job_count: 1000
  job_batch_size: 10
  job_generation_interval: 1200.
  flops_lower_bound: 6000.
  flops_upper_bound: 6000.
  memory_lower_bound: 1
  memory_upper_bound: 8
  cores_lower_bound: 1
  cores_upper_bound: 2
  delay_lower_bound: 3000.
  delay_upper_bound: 3000.
  min_quorum_lower_bound: 1
  min_quorum_upper_bound: 3
  target_nresults_redundancy: 2
  input_size_lower_bound: 5
  input_size_upper_bound: 20
  network_latency: 0.5
  network_bandwidth: 1000
  local_latency: 0.0
  local_bandwidth: 10000
  report_status_interval: 6000.

server:
  shared_memory_size: 50
  local_latency: 0.0
  local_bandwidth: 10000
  report_status_interval: 6000.
  assimilator:
    interval: 1200.
  validator:
    interval: 3000.
  transitioner:
    interval: 1200.
  db_purger:
    interval: 3600.
  file_deleter:
    interval: 3600.
  feeder:
    interval: 3600.
  scheduler:
    interval: 1500.

  data_server:
    disk_capacity: 25000
    disk_read_bandwidth: 2000.
    disk_write_bandwidth: 2000.
