seed: 95
sim_duration: 100.

clients:
  - count: 500
    cpu:
      speed: 5.5
      cores: 1
    work_fetch_interval: 1.
    buffered_work_min: 4.
    buffered_work_max: 12.
    memory: 8
    disk_capacity: 128
    disk_read_bandwidth: 400.
    disk_write_bandwidth: 200.
    network_latency: 40
    network_bandwidth: 70
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 1.
    reliability_distribution:
      Uniform:
        min: 0.8
        max: 1.
    availability_distribution:
      Weibull:
        scale: 2.964
        shape: 0.393
    unavailability_distribution:
      LogNormal:
        mu: -0.586
        sigma: 2.844
  # - trace: trace.csv
  #   work_fetch_interval: 3600.
  #   buffered_work_min: 10800.
  #   buffered_work_max: 21600.
  #   memory: 8
  #   disk_capacity: 256
  #   disk_read_bandwidth: 400.
  #   disk_write_bandwidth: 200.
  #   network_latency: 40
  #   network_bandwidth: 70
  #   local_latency: 0.0
  #   local_bandwidth: 10000
  #   report_status_interval: 1800.
  #   reliability_distribution:
  #     Uniform:
  #       min: 0.8
  #       max: 1.
  #   availability_distribution:
  #     Weibull:
  #       scale: 2.964
  #       shape: 0.393
  #   unavailability_distribution:
  #     LogNormal:
  #       mu: -0.586
  #       sigma: 2.844

server:
  local_latency: 0.0
  local_bandwidth: 10000
  report_status_interval: 0.5
  assimilator:
    interval: 3.
  validator:
    interval: 1.
  transitioner:
    interval: 0.25
  db_purger:
    interval: 3.
  file_deleter:
    interval: 4.
  feeder:
    shared_memory_size: 20000
    interval: 0.2

  data_server:
    disk_capacity: 1000000
    disk_read_bandwidth: 700.
    disk_write_bandwidth: 500.
  
  job_generator:
    gflops_min: 7500.
    gflops_max: 7500.
    memory_min: 10
    memory_max: 30
    cores_min: 1
    cores_max: 1
    delay_min: 30.
    delay_max: 30.
    min_quorum_min: 1
    min_quorum_max: 1
    target_nresults_redundancy: 0
    input_size_min: 5
    input_size_max: 20
    output_size_min: 5
    output_size_max: 20
