seed: 32
sim_duration: 3.

clients:
  - count: 10
    speed: 8.
    cpus: 4
    work_fetch_interval: 1300.
    buffered_work_lower_bound: 1200.
    buffered_work_upper_bound: 2400.
    memory: 4
    disk_capacity: 5000
    disk_read_bandwidth: 2000.
    disk_write_bandwidth: 2000.
    network_latency: 0.5
    network_bandwidth: 1000
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 600.

server:
  shared_memory_size: 50
  local_latency: 0.0
  local_bandwidth: 10000
  report_status_interval: 600.
  assimilator:
    interval: 600.
  validator:
    interval: 300.
  transitioner:
    interval: 270.
  db_purger:
    interval: 1200.
  file_deleter:
    interval: 1200.
  feeder:
    interval: 600.
  scheduler:
    interval: 0.

  data_server:
    disk_capacity: 500000
    disk_read_bandwidth: 10000.
    disk_write_bandwidth: 10000.
  
  job_generator:
    job_count: 1000
    job_batch_size: 10
    job_generation_interval: 1200.
    flops_lower_bound: 60000.
    flops_upper_bound: 60000.
    memory_lower_bound: 1
    memory_upper_bound: 8
    cores_lower_bound: 1
    cores_upper_bound: 2
    delay_lower_bound: 36000.
    delay_upper_bound: 36000.
    min_quorum_lower_bound: 1
    min_quorum_upper_bound: 3
    target_nresults_redundancy: 2
    input_size_lower_bound: 5
    input_size_upper_bound: 20
    output_size_lower_bound: 5
    output_size_upper_bound: 20
    network_latency: 0.5
    network_bandwidth: 1000
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 600.
