seed: 32
sim_duration: 1.

clients:
  - count: 2
    speed: 8.
    cpus: 4
    work_fetch_interval: 1300.
    buffered_work_lower_bound: 1200.
    buffered_work_upper_bound: 2400.
    memory: 4
    disk_capacity: 5000
    disk_read_bandwidth: 2000.
    disk_write_bandwidth: 2000.
    network_latency: 0.5
    network_bandwidth: 1000
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 600.
    reliability_distribution:
      Uniform:
        min: 0.8
        max: 1.
    availability_distribution:
      Weibull:
        scale: 2.964
        shape: 0.393
    unavailability_distribution:
      LogNormal:
        mu: -0.586
        sigma: 2.844

server:
  local_latency: 0.0
  local_bandwidth: 10000
  report_status_interval: 600.
  assimilator:
    interval: 600.
  validator:
    interval: 300.
  transitioner:
    interval: 270.
  db_purger:
    interval: 1200.
  file_deleter:
    interval: 1200.
  feeder:
    shared_memory_size: 100
    interval: 600.
  scheduler:
    interval: 0.

  data_server:
    disk_capacity: 500000
    disk_read_bandwidth: 10000.
    disk_write_bandwidth: 10000.
  
  job_generator:
    job_count: 1000
    job_batch_size: 10
    job_generation_interval: 1200.
    flops_lower_bound: 6000.
    flops_upper_bound: 6000.
    memory_lower_bound: 1
    memory_upper_bound: 8
    cores_lower_bound: 1
    cores_upper_bound: 2
    delay_lower_bound: 36000.
    delay_upper_bound: 36000.
    min_quorum_lower_bound: 1
    min_quorum_upper_bound: 1
    target_nresults_redundancy: 0
    input_size_lower_bound: 5
    input_size_upper_bound: 20
    output_size_lower_bound: 5
    output_size_upper_bound: 20
    network_latency: 0.5
    network_bandwidth: 1000
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 600.
