seed: 32

clients:
  - count: 10
    speed: 8.
    cpus: 4
    work_fetch_interval: 55.
    buffered_work_lower_bound: 50.
    buffered_work_upper_bound: 200.
    memory: 4
    disk_capacity: 5000
    disk_read_bandwidth: 2000.
    disk_write_bandwidth: 2000.
    network_latency: 0.5
    network_bandwidth: 1000
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 100.


job_generator:
  job_count: 1000
  job_batch_size: 10
  job_generation_interval: 20.
  flops_lower_bound: 100.
  flops_upper_bound: 100.
  memory_lower_bound: 1
  memory_upper_bound: 8
  cores_lower_bound: 1
  cores_upper_bound: 2
  delay_lower_bound: 50.
  delay_upper_bound: 50.
  min_quorum_lower_bound: 1
  min_quorum_upper_bound: 3
  target_nresults_redundancy: 2
  input_size_lower_bound: 5
  input_size_upper_bound: 20
  network_latency: 0.5
  network_bandwidth: 1000
  local_latency: 0.0
  local_bandwidth: 10000
  report_status_interval: 100.

server:
  shared_memory_size: 50
  local_latency: 0.0
  local_bandwidth: 10000
  report_status_interval: 100.
  assimilator:
    interval: 20.
  validator:
    interval: 50.
  transitioner:
    interval: 20.
  db_purger:
    interval: 60.
  file_deleter:
    interval: 60.
  feeder:
    interval: 60.
  scheduler:
    interval: 25.

  data_server:
    disk_capacity: 25000
    disk_read_bandwidth: 2000.
    disk_write_bandwidth: 2000.
