seed: 32
sim_duration: 24.

clients:
  - count: 100000
    cpu:
      speed: 10.
      cores: 8
    work_fetch_interval: 1300.
    buffered_work_min: 1200.
    buffered_work_max: 2400.
    memory: 4
    disk_capacity: 5000
    disk_read_bandwidth: 2000.
    disk_write_bandwidth: 2000.
    network_latency: 0.5
    network_bandwidth: 1000
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 600.
    reliability_distribution:
      Uniform:
        min: 0.8
        max: 1.
    availability_distribution:
      Weibull:
        scale: 2.964
        shape: 0.393
    unavailability_distribution:
      LogNormal:
        mu: -0.586
        sigma: 2.844
  - trace: trace.csv
    work_fetch_interval: 1300.
    buffered_work_min: 1200.
    buffered_work_max: 2400.
    memory: 4
    disk_capacity: 5000
    disk_read_bandwidth: 2000.
    disk_write_bandwidth: 2000.
    network_latency: 0.5
    network_bandwidth: 1000
    local_latency: 0.0
    local_bandwidth: 10000
    report_status_interval: 600.
    reliability_distribution:
      Uniform:
        min: 0.8
        max: 1.
    availability_distribution:
      Weibull:
        scale: 2.964
        shape: 0.393
    unavailability_distribution:
      LogNormal:
        mu: -0.586
        sigma: 2.844

server:
  local_latency: 0.0
  local_bandwidth: 10000
  report_status_interval: 600.
  assimilator:
    interval: 600.
  validator:
    interval: 300.
  transitioner:
    interval: 270.
  db_purger:
    interval: 1200.
  file_deleter:
    interval: 1200.
  feeder:
    shared_memory_size: 20000
    interval: 600.
  scheduler:
    interval: 0.

  data_server:
    disk_capacity: 5000000
    disk_read_bandwidth: 10000.
    disk_write_bandwidth: 10000.
  
  job_generator:
    flops_min: 200000.
    flops_max: 200000.
    memory_min: 1
    memory_max: 8
    cores_min: 1
    cores_max: 2
    delay_min: 36000.
    delay_max: 36000.
    min_quorum_min: 1
    min_quorum_max: 3
    target_nresults_redundancy: 2
    input_size_min: 50
    input_size_max: 200
    output_size_min: 50
    output_size_max: 200
